sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - SITEC_MOCK_VERSION=0.56.0
  matrix:
    - AUTOLOAD=1
    - AUTOLOAD=0

cache:
  directories:
    - $HOME/.composer/cache/files
    - sierratecnologia-mock

before_install:
  # Install various build dependencies. We use `travis_retry` because Composer
  # will occasionally fail intermittently.
  - travis_retry composer install

  # Unpack and start sierratecnologia-mock so that the test suite can talk to it
  - |
    if [ ! -d "sierratecnologia-mock/sierratecnologia-mock_${SITEC_MOCK_VERSION}" ]; then
      mkdir -p sierratecnologia-mock/sierratecnologia-mock_${SITEC_MOCK_VERSION}/
      curl -L "https://github.com/sierratecnologia/sierratecnologia-mock/releases/download/v${SITEC_MOCK_VERSION}/sierratecnologia-mock_${SITEC_MOCK_VERSION}_linux_amd64.tar.gz" -o "sierratecnologia-mock/sierratecnologia-mock_${SITEC_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "sierratecnologia-mock/sierratecnologia-mock_${SITEC_MOCK_VERSION}_linux_amd64.tar.gz" -C "sierratecnologia-mock/sierratecnologia-mock_${SITEC_MOCK_VERSION}/"
    fi
  - |
    sierratecnologia-mock/sierratecnologia-mock_${SITEC_MOCK_VERSION}/sierratecnologia-mock > /dev/null &
    SITEC_MOCK_PID=$!
  - export PATH="${PATH}:${PWD}/sierratecnologia-mock/sierratecnologia-mock_${SITEC_MOCK_VERSION}"

script: ./build.php ${AUTOLOAD}

after_script: ./vendor/bin/coveralls -v
